#!/bin/bash

tocver=$(grep -E "Version" "Interface/Addons/RayUI/RayUI.toc" | sed "s/.*build\s*\(.*\)$/\1/g")
buildver=$(git rev-list HEAD | wc -l)
if test "$tocver" = "$buildver"
then
	exit 0
else
	echo "Bumping toc version.."
	sed -i "s/build.*$/build $buildver/g" `grep build.*$ -rl ./Interface/Addons/RayUI/RayUI.toc`
	exit 1
fi
