if ( GetLocale() == "zhCN" ) then 
	FRIENDS_MENU_XP_LOADED = "FriendsMenuXP加载成功, 作者Warbaby-二区暗影之月<凌翼>."
	FRIENDS_MENU_XP_CANNOT_TARGET = "FriendsMenuXP无法选定<$name$>为目标。"

	FMXP_BUTTON_ADD_FRIEND = "加为好友"
	FMXP_BUTTON_SEND_WHO = "查询详情"
	FMXP_BUTTON_ADD_GUILD = "工会邀请"
	FMXP_BUTTON_GET_NAME = "复制名字"
	FMXP_BUTTON_TRADE = "交易"
	FMXP_BUTTON_GUILD_LEAVE = "退出工會！"
	FMXP_BUTTON_GUILD_PROMOTE = "提升该会员"
	FMXP_BUTTON_PVP_REPORT_AFK = "举报混子"
	FMXP_BUTTON_SET_FOCUS = "设为焦点"
	FMXP_BUTTON_PROMOTE = "提升为队长"
	FMXP_BUTTON_LOOT_PROMOTE = "设为拾取者"
	FMXP_BUTTON_ACHIEVEMENTS = "对比成就"
	FMXP_BUTTON_ARMORY = "英雄榜"
end