FRIENDS_MENU_XP_LOADED = nil
FRIENDS_MENU_XP_CANNOT_TARGET = "FriendsMenuXP can't target <$name$>."

FMXP_BUTTON_ADD_FRIEND = "Add Friend"
FMXP_BUTTON_SEND_WHO = "Query Detail"
FMXP_BUTTON_ADD_GUILD = "Guild Invite"
FMXP_BUTTON_GET_NAME = "Get Name"
FMXP_BUTTON_TRADE = "Trade"
FMXP_BUTTON_GUILD_LEAVE = "Leave Guild!!"
FMXP_BUTTON_GUILD_PROMOTE = "Guild Promote"
FMXP_BUTTON_PVP_REPORT_AFK = "Report AFK"
FMXP_BUTTON_SET_FOCUS = "Set Focus"
FMXP_BUTTON_PROMOTE = "Promote"
FMXP_BUTTON_LOOT_PROMOTE = "Looter"
FMXP_BUTTON_ACHIEVEMENTS = "Achievements"
FMXP_BUTTON_ARMORY = "Armory"

