local R, L, P = unpack(select(2, ...)) --Inport: Engine, Locales, ProfileDB
local S = R:GetModule("Skins")

local function LoadSkin()
	S:SetBD(ReforgingFrame)
	select(12,ReforgingFrameItemButton:GetRegions()):Hide()
	ReforgingFrame:DisableDrawLayer("BACKGROUND")
	ReforgingFrame:DisableDrawLayer("BORDER")
	ReforgingFramePortrait:Hide()
	ReforgingFrameBg:Hide()
	ReforgingFrameTitleBg:Hide()
	ReforgingFramePortraitFrame:Hide()
	ReforgingFrameTopBorder:Hide()
	ReforgingFrameTopRightCorner:Hide()
	ReforgingFrameRestoreButton_LeftSeparator:Hide()
	ReforgingFrameRestoreButton_RightSeparator:Hide()
	ReforgingFrameButtonFrame:GetRegions():Hide()
	ReforgingFrameButtonFrameButtonBorder:Hide()
	ReforgingFrameButtonFrameButtonBottomBorder:Hide()
	ReforgingFrameButtonFrameMoneyLeft:Hide()
	ReforgingFrameButtonFrameMoneyRight:Hide()
	ReforgingFrameButtonFrameMoneyMiddle:Hide()
	ReforgingFrameMissingFadeOut:SetAlpha(0)
	ReforgingFrameRestoreMessage:SetTextColor(1, 1, 1)
	S:Reskin(ReforgingFrameRestoreButton)
	S:Reskin(ReforgingFrameReforgeButton)
	S:ReskinClose(ReforgingFrameCloseButton)
	ReforgingFrameRestoreButton:ClearAllPoints()
	ReforgingFrameRestoreButton:SetPoint("LEFT", ReforgingFrameMoneyFrame, "RIGHT", 60, 0)
	ReforgingFrameReforgeButton:ClearAllPoints()
	ReforgingFrameReforgeButton:SetPoint("LEFT", ReforgingFrameRestoreButton, "RIGHT", 1, 0)
end

S:RegisterSkin("Blizzard_ReforgingUI", LoadSkin)